## NUMPY ##

In [1]:
my_list = [12,34,56]
print(my_list)

[12, 34, 56]


In [2]:
import numpy as np
arr = np.array([12,34,56,78])
print(arr)

[12 34 56 78]


#### USING PYTHON LIST ####

In [7]:
my_list = [1,2,3]
my_list2 = [4,5,6]
total = []
for i in range(len(my_list)):
    total.append(my_list[i] + my_list2[i])
print(total)

[5, 7, 9]


#### USING NUMPY ####

In [11]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


#### TYPES OF ARRAY AND ATTRIBUTES ####

In [24]:
import numpy as np
#1D array
arr=np.array([1,2,3,4,5])
#2D array
arr1 = np.array([[1,2,3],[4,5,6]])
#multidimentional array
arr2 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(arr)
print(arr1)
print(arr2)
print(arr2.shape)
print(arr1.shape)
print(arr2.ndim) 
print(arr1.ndim)
print(arr2.size)
print(arr1.size)
print(arr2.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
(2, 3)
3
2
9
6
int64


#### ARRAY CREATION IN NUMPY ####

In [60]:
import numpy as np
a = np.array([1,2,3,4.5])
b = np.zeros(5)
print(a)
print(b)
c = np.zeros((2,2))
print(c)
d = np.ones(3)
print(d)
e = np.ones((2,3))
print(e)


print(np.arange(1,10,2))
print(np.linspace(0,20,5))
print(np.random.rand(5))
print(np.random.randint(1,100,10))
print(np.random.randn(5))


[1.  2.  3.  4.5]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[ 0.  5. 10. 15. 20.]
[0.47324491 0.10815809 0.07861896 0.35193487 0.65283788]
[93  7 29 57 49 81 72 93 16 77]
[ 0.2562272   0.17485032 -0.74178587 -1.16157225  0.34494809]


#### INDEXING AND SLICING ####

In [86]:
#1d array indexing
import numpy as np
arr = np.array([10,20,35,48,50,60,70,80])
print(arr[0])
print(arr[-1])


#2d array indexing
arr2 = np.array([[10,20,30],
                 [40,50,60],
                 [22,33,44]])
print(arr2[1][1])


# 1D array slicing
print(arr[2:7])
print(arr[-7:-1])
print(arr[:5])
print(arr[2:])
print(arr[::2])

# 2D array slicing
print(arr2[2])
print(arr2[:,2])


#boolean indexing
print(arr[arr>60])
print(arr[arr%2==0])

#fancy indexing
print(arr[[0,3,6]])

arr[2]=100
print(arr)

10
80
50
[35 48 50 60 70]
[20 35 48 50 60 70]
[10 20 35 48 50]
[35 48 50 60 70 80]
[10 35 50 70]
[22 33 44]
[30 60 44]
[70 80]
[10 20 48 50 60 70 80]
[10 48 70]
[ 10  20 100  48  50  60  70  80]


#### MATHEMATICAL OPERATIONS IN NUMPY ####

In [92]:
#1D Scalar Broadcasting
import numpy as np
a = np.array([1,2,3])
print(a+10)

#2D Scalar Broadcasting
b = np.array([[1,2,3],
              [4,5,6]])
print(b+10)

#Row Broadcasting
#always no of columns must be same
print(b+a)

[11 12 13]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


#### matrix operations ####

In [101]:
import numpy as np
a = np.array([[1,2],
             [4,5]])
b = np.array([[3,4],
             [5,6]])
print(a*b)
print(np.dot(a,b))
print(a@b)
print(np.matmul(a,b))

#Array Transpose 
print(a.T) #Row becomes Column

[[ 3  8]
 [20 30]]
[[13 16]
 [37 46]]
[[13 16]
 [37 46]]
[[13 16]
 [37 46]]
[[1 4]
 [2 5]]


#### UNIVERSAL MATHEMATICAL FUNCTION ####

In [105]:
import numpy as np
a = np.array([4,9,16])
print(np.sqrt(a))

#Absolute value
b = np.array([-4,-9,-16])
print(np.abs(b))

#log values
print(np.log(a))

#exponential
print(np.exp(a))

[2. 3. 4.]
[ 4  9 16]
[1.38629436 2.19722458 2.77258872]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [8]:
#Round function
import numpy as np
arr = np.array([1.234,5,674])
print(np.round(arr,2))
print(np.ceil(arr))
print(np.floor(arr))

[  1.23   5.   674.  ]
[  2.   5. 674.]
[  1.   5. 674.]


#### STATISTICAL FUNCTION ####

In [28]:
#statistical function
import numpy as np
a = np.array([10,20,30,40,50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.percentile(a,25))
print(np.var(a))
print(np.argmin(a))
print(np.argmax(a))

b = np.array([1,2,3,4,5])
c = np.array([2,4,6,8,10])
print(np.corrcoef(b,c))


30.0
30.0
14.142135623730951
50
10
150
20.0
200.0
0
4
[[1. 1.]
 [1. 1.]]


#### AGGREGATE FUNCTION ####

In [32]:
import numpy as np
a = np.array([[10,20,30],
              [40,50,60]])
print(np.sum(a))
print(np.sum(a,axis=0)) #Column wise
print(np.sum(a,axis=1)) #Row wise


210
[50 70 90]
[ 60 150]


In [52]:
import numpy as np
scores = np.array([[45,67,89],
                 [60,70,80],
                 [90,40,80]])
print(scores)

print(np.mean(scores))

print(np.sum(scores,axis=0))
print(np.sum(scores,axis=1))


min_score = np.min(scores)
max_score = np.max(scores)

print(np.mean(scores,axis=0))

normalized_scores = (scores - min_score) / (max_score - min_score)
print(normalized_scores)

[[45 67 89]
 [60 70 80]
 [90 40 80]]
69.0
[195 177 249]
[201 210 210]
[65. 59. 83.]
[[0.1  0.54 0.98]
 [0.4  0.6  0.8 ]
 [1.   0.   0.8 ]]


In [59]:
import numpy as np
arr = np.array([10,20,30,40,50])
exp = arr[arr>25]
print(exp)
print(sum(exp))

[30 40 50]
120
